require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  RubyInterpreters:
    - ruby
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper\.rb'
    - 'spec/spec_helper\.rb'
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: either
Style/RaiseArgs:
  EnforcedStyle: exploded
Style/RedundantFetchBlock:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 12
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/**/*'
    - 'spec/views/**/*'
    - 'spec/lint/rubocop_spec.rb'
RSpec/FactoryBot/ConsistentParenthesesStyle:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
